services:
  tab-api:
    container_name: tab-api
    image: tab-api
    ports:
      - "3333:3333"
    env_file: ./tab-api/.env
    volumes:
      - ./tab-api:/app
    networks:
      - main_network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: tab-api
      POSTGRES_DB: tab-api
      POSTGRES_PASSWORD: tab-api
    ports:
      - "5555:5432"
    volumes:
      - ./.data/postgres-data:/var/lib/postgresql/data
    networks:
      - main_network

  redis:
    image: redis
    ports:
      - "6699:6379"
    networks:
      - main_network

networks:
  main_network:
    driver: bridge
