FROM node:lts-alpine

WORKDIR /app

COPY ./src .

RUN npm i -g @adonisjs/cli

ARG NODE_ENV
ENV ARG=${ARG}

ARG PORT
ENV PORT=${PORT}

ARG HOST
ENV HOST=${HOST}

ARG APP_KEY
ENV APP_KEY=${APP_KEY}

ARG DRIVE_DISK
ENV DRIVE_DISK=${DRIVE_DISK}

ARG DB_CONNECTION
ENV DB_CONNECTION=${DB_CONNECTION}

ARG PG_HOST
ENV PG_HOST=${PG_HOST}

ARG PG_PORT
ENV PG_PORT=${PG_PORT}

ARG PG_USER
ENV PG_USER=${PG_USER}

ARG PG_PASSWORD
ENV PG_PASSWORD=${PG_PASSWORD}

ARG PG_DB_NAME
ENV PG_DB_NAME=${PG_DB_NAME}

ARG SMTP_HOST
ENV SMTP_HOST=${SMTP_HOST}

ARG SMTP_PORT
ENV SMTP_PORT=${SMTP_PORT}

ARG SMTP_USERNAME
ENV SMTP_USERNAME=${SMTP_USERNAME}

ARG SMTP_PASSWORD
ENV SMTP_PASSWORD=${SMTP_PASSWORD}

ARG MAIL_DOMAIN
ENV MAIL_DOMAIN=${MAIL_DOMAIN}

ARG CACHE_VIEWS
ENV CACHE_VIEWS=${CACHE_VIEWS}

ARG APP_URL
ENV APP_URL=${APP_URL}

ARG REDIS_HOST
ENV REDIS_HOST=${REDIS_HOST}

ARG REDIS_PORT
ENV REDIS_PORT=${REDIS_PORT}

EXPOSE ${PORT}

ADD docker-entrypoint.sh /usr/local/bin/

RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
